/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author USUARIO
 */
public class GestionCantidades extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionCantidades.class.getName());

    /**
     * Creates new form GestionCantidades
     */
    public GestionCantidades() {
        initComponents();
        setTitle("Inventra | Movimiento de Inventario | ");
        setResizable(false);
        setLocationRelativeTo(null);
        jpSalida.setEnabled(false);
        txtCantSalida.setEnabled(false);
        txtObservacionSalida.setEnabled(false);                              
        jpEntrada.setEnabled(false);
        txtCantEntrada.setEnabled(false);
        txtObservacionEntrada.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jpEntrada = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtCantEntrada = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtObservacionEntrada = new javax.swing.JTextField();
        jpSalida = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCantSalida = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtObservacionSalida = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre producto");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jTextField1.setEnabled(false);
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 300, -1));

        jLabel2.setText("Codigo producto");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, -1));

        jLabel3.setText("Tipo");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        jComboBox1.setEnabled(false);
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 170, -1));

        jLabel7.setText("Categoria");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Normal");
        jRadioButton3.setEnabled(false);
        jPanel2.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 42, -1, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Especial");
        jRadioButton4.setEnabled(false);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 42, -1, -1));

        jButton5.setText("Buscar");
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 80, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 110));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion Cantidades"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpEntrada.setBorder(javax.swing.BorderFactory.createTitledBorder("Entradas"));
        jpEntrada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Cantidad entrada");
        jpEntrada.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jpEntrada.add(txtCantEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 102, -1));

        jLabel6.setText("Observación");
        jpEntrada.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));
        jpEntrada.add(txtObservacionEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 250, -1));

        jPanel1.add(jpEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 400, 80));

        jpSalida.setBorder(javax.swing.BorderFactory.createTitledBorder("Salidas"));
        jpSalida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Cantidad salida");
        jpSalida.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 18, -1, -1));
        jpSalida.add(txtCantSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 102, -1));

        jLabel8.setText("Observación");
        jpSalida.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 18, -1, -1));
        jpSalida.add(txtObservacionSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 240, -1));

        jPanel1.add(jpSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 390, 80));

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("Entrada");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Salida");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jButton1.setText("Realizara el movimiento");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 116, 808, 150));

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Movimientos"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Tipo Movimiento", "Cantidad", "Observación"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 780, 130));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 800, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        jpEntrada.setEnabled(true);
        jpSalida.setEnabled(false);
        txtCantSalida.setText("");
        txtObservacionSalida.setText("");
        txtCantSalida.setEnabled(false);
        txtObservacionSalida.setEnabled(false);
        txtCantEntrada.setEnabled(true);
        txtObservacionEntrada.setEnabled(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        jpEntrada.setEnabled(false);
        jpSalida.setEnabled(true);
        txtCantEntrada.setText("");
        txtObservacionEntrada.setText("");
        txtCantSalida.setEnabled(true);
        txtObservacionSalida.setEnabled(true);
        txtCantEntrada.setEnabled(false);
        txtObservacionEntrada.setEnabled(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GestionCantidades().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel jpEntrada;
    private javax.swing.JPanel jpSalida;
    private javax.swing.JTextField txtCantEntrada;
    private javax.swing.JTextField txtCantSalida;
    private javax.swing.JTextField txtObservacionEntrada;
    private javax.swing.JTextField txtObservacionSalida;
    // End of variables declaration//GEN-END:variables
}
